name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        target: default
        arch: x86_64
      
    - name: Install Cordova
      run: npm install -g cordova@12.0.0
      
    - name: Create Cordova project
      run: |
        cordova create tetris-android com.suemuBai.tetris "俄罗斯方块"
        cd tetris-android
        cp ../index.html www/index.html
        cp ../game.js www/game.js
        cp ../config-simple.xml config.xml
        
    - name: Add Android platform (specific version)
      run: |
        cd tetris-android
        cordova platform add android@12.0.1
        
    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
    - name: Install required SDK packages
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.2" "platform-tools"
        
    - name: Set Gradle permissions
      run: |
        cd tetris-android/platforms/android
        chmod +x gradlew
        
    - name: Build APK with specific Gradle version
      run: |
        cd tetris-android
        export GRADLE_OPTS="-Xmx4g -Dorg.gradle.daemon=false"
        cordova build android --debug --verbose --gradleArg="--warning-mode=all"
        
    - name: List build outputs (for debugging)
      if: always()
      run: |
        echo "Listing all APK files..."
        find tetris-android -name "*.apk" -type f || echo "No APK files found"
        echo "Listing platforms directory..."
        ls -la tetris-android/platforms/android/app/build/outputs/ || echo "Build outputs directory not found"
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: tetris-debug-apk
        path: tetris-android/platforms/android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload any APK files found
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: all-apk-files
        path: tetris-android/**/*.apk