name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        target: default
        arch: x86_64
      
    - name: Install Cordova
      run: npm install -g cordova@latest
      
    - name: Create Cordova project
      run: |
        cordova create tetris-android com.suemuBai.tetris "俄罗斯方块"
        cd tetris-android
        cp ../index.html www/index.html
        cp ../game.js www/game.js
        cp ../config-simple.xml config.xml
        
    - name: Add Android platform
      run: |
        cd tetris-android
        cordova platform add android@latest
        
    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
    - name: Build APK
      run: |
        cd tetris-android
        cordova build android --verbose
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: tetris-debug-apk
        path: tetris-android/platforms/android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: List build outputs (for debugging)
      if: always()
      run: |
        echo "Listing build outputs..."
        find tetris-android/platforms/android/app/build/outputs -name "*.apk" -type f || echo "No APK files found"